In [1]:
import numpy as np

In [4]:
arr1=np.array([[1, 2, 3]])
arr1

array([[1, 2, 3]])

In [5]:
arr1.shape

(1, 3)

In [6]:
arr2=np.array([[1, 2, 3], [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr2.shape

(2, 3)

In [8]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [9]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
arr1.dtype

dtype('int64')

In [13]:
# numpy vectorisation
arr1=np.array([[1, 2, 3], [4, 5, 6]])
arr2=np.array([[7, 8, 9], [10, 11, 12]])

arr1 + arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [14]:
arr1-arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [16]:
np.sqrt(arr2)

array([[2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162]])

In [18]:
np.log(arr2)

array([[1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665]])

In [19]:
# universal functions (ufuncs) are functions that operate on ndarrays elementwise, producing an ndarray as output. They are fast, vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.

In [20]:
# slicing and indexing
arr1[0, 1]  # access the element at row 0, column 1

np.int64(2)

In [23]:
arr2[0, :]  # access the first row

array([7, 8, 9])

In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[1:2, 1:3]  # access a subarray from row 1 to 2 and column 1 to 3

array([[5, 6]])